const img = (name) => `${new URL("../", import.meta.url).pathname}images/${name}.webp`;
export const studio = {
  name: 'PRESCORN', email: '', inquiryEndpoint: globalThis.PRESCORN_CONFIG?.inquiryEndpoint || '',
  navigation: [{label:'Work',href:'#/work'},{label:'Studio',href:'#/studio'},{label:'Pricing',href:'#/pricing'}],
  pricing: [
    {name:'Essential',price:'€800',prefix:'Starting from',description:'A focused introduction. A lasting first impression.',features:['Landing pages & smaller websites','Custom visual direction','Responsive development','Launch & essentials'],budget:'Under €1,000'},
    {name:'Signature',price:'€1,500',prefix:'Starting from',description:'Your brand, expressed in a complete digital home.',features:['Complete custom studio websites','Bespoke page design','Thoughtful interactions','Performance & launch'],budget:'€1,000–€2,500'},
    {name:'Experience',price:'Custom quote',prefix:'Made to measure',description:'For ideas that deserve something extraordinary.',features:['Cinematic art direction','Advanced interaction & motion','3D & immersive experiences','A scope built around your idea'],budget:'Not sure yet'}
  ],
  services:['Website','E-commerce','Portfolio','Landing Page','Interactive Experience','Other'],
  budgets:['Under €1,000','€1,000–€2,500','€2,500–€5,000','€5,000+','Not sure yet']
};
export const projects = [
 {slug:'sillage',name:'SILLAGE / 09',category:'Fragrance / Digital Experience',short:'An invisible presence.',description:'A fragrance concept translated into an atmospheric digital world. Product storytelling, tactile imagery and carefully paced interactions bring the invisible character of scent into view.',liveUrl:'https://budaqovabdullah2005-ship-it.github.io/sillage/',featured:true,color:'#26392e',concept:true},
 {slug:'aurel',name:'AUREL',category:'Jewellery / Digital Experience',short:'Objects of fascination.',description:'A cinematic jewellery concept built around material, light and movement. An expressive presentation that invites visitors to explore the details behind each object.',liveUrl:'https://budaqovabdullah2005-ship-it.github.io/AUREL/',featured:true,color:'#5b3825',concept:true,liveStatus:'unavailable'},
 {slug:'varel',name:'VAREL',category:'Watches / Interactive 3D',short:'Time, deconstructed.',description:'A watch concept explored through an interactive mechanical object. Finish selection and a scroll-led journey reveal the architecture beneath the dial.',liveUrl:'https://qabil05.github.io/varel/',featured:true,color:'#202b33',concept:true,assetAvailable:false},
 {slug:'sheh',name:'SHEH',category:'Skincare / Brand Website',short:'The first touch of nature.',description:'A bright skincare concept shaped by water, botanical ingredients and daily rituals. An editorial storefront connects a considered product collection with a softer approach to care.',liveUrl:'https://qabil05.github.io/sheh-skincare-project/',color:'#e4e7d8',concept:true},
 {slug:'orven',name:'ORVEN',category:'Architecture / Portfolio',short:'Formed by place.',description:'An architectural portfolio concept with a disciplined grid and generous imagery. Projects, materials and spatial details are presented with the quiet precision of the work itself.',liveUrl:'https://qabil05.github.io/orven-architecture/',color:'#d9d7ce',concept:true},
 {slug:'mirbir',name:'MIRBIR',category:'Hospitality / Brand Website',short:'A slower kind of escape.',description:'A boutique hotel concept inspired by sea, stone and silence. Warm destination imagery and an intuitive browsing experience establish a sense of place before arrival.',liveUrl:'https://qabil05.github.io/mirbir-hotel-project/',color:'#76756a',concept:true},
 {slug:'prsmyn',name:'PRSMYN',category:'Technology / Brand Website',short:'A clearer perspective.',description:'A digital introduction to a technology venture, bringing its purpose, research and story together in a direct, approachable brand website.',liveUrl:'https://prsmyn.com/',color:'#bdc4ec',concept:false},
 {slug:'renovoltis',name:'RENOVOLTIS',category:'Sustainability / Brand Website',short:'A forward-looking outlook.',description:'A sustainability-focused website in the PRESCORN project collection. Visit the live website to explore the project.',liveUrl:'https://renovoltis.com/',color:'#dee2ce',concept:false,assetAvailable:false,liveStatus:'unverified'}
].map((p,i)=>({...p,number:String(i+1).padStart(2,'0'),role:'Design & development',year:null,coverImage:img(p.slug),desktopImage:img(p.slug),mobileImage:null,previewType:'external',liveStatus:'unverified',assetAvailable:true,...p}));
